[package]
name = "rover-desktop-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
druid = { version = "0.8.3", features = ["im", "image", "svg"] }
image = "0.24.7"
